using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KafkaInv.Configurations
{
    public class EnvironmentVariablesConstants
    {
        public const string POLICY_NUMERO_RETENTATIVAS = "NUMERO_RETENTATIVAS";
        public const string POLICY_CIRCUIT_BREAKER_NUMERO_ERROS_ACEITOS_ANTES_QUEBRA = "CIRCUIT_BREAKER_NUMERO_ERROS_ACEITOS_ANTES_QUEBRA";
        public const string POLICY_CIRCUIT_BREAKER_DURACAO_QUEBRA = "CIRCUIT_BREAKER_DURACAO_QUEBRA";
        public const string LINX_TIMEOUT_SEGUNDOS = "LINX_TIMEOUT_SEGUNDOS";

        public const string MONKEY_POLICY_INTERNAL_SERVER_ERROR_ATIVO = "MONKEY_INTERNAL_SERVER_ERROR_ATIVO";
        public const string MONKEY_POLICY_INTERNAL_SERVER_ERROR_PORCENTAGEM = "MONKEY_INTERNAL_SERVER_ERROR_PORCENTAGEM";

        public const string MONKEY_POLICY_NOT_FOUND_ATIVO = "MONKEY_NOT_FOUND_ATIVO";
        public const string MONKEY_POLICY_NOT_FOUND_PORCENTAGEM = "MONKEY_NOT_FOUND_PORCENTAGEM";

        public const string MONKEY_POLICY_REQUEST_TIMEOUT_ATIVO = "MONKEY_REQUEST_TIMEOUT_ATIVO";
        public const string MONKEY_POLICY_REQUEST_TIMEOUT_PORCENTAGEM = "MONKEY_REQUEST_TIMEOUT_PORCENTAGEM";
        public const string MONKEY_POLICY_REQUEST_TIMEOUT_SEGUNDOS = "MONKEY_REQUEST_TIMEOUT_SEGUNDOS";

        public const string MONKEY_POLICY_BAD_GATEWAY_ATIVO = "MONKEY_BAD_GATEWAY_ATIVO";
        public const string MONKEY_POLICY_BAD_GATEWAY_PORCENTAGEM = "MONKEY_BAD_GATEWAY_PORCENTAGEM";

        public const string MONKEY_POLICY_GATEWAY_TIMEOUT_ATIVO = "MONKEY_GATEWAY_TIMEOUT_ATIVO";
        public const string MONKEY_POLICY_GATEWAY_TIMEOUT_PORCENTAGEM = "MONKEY_GATEWAY_TIMEOUT_PORCENTAGEM";
        public const string MONKEY_POLICY_GATEWAY_TIMEOUT_SEGUNDOS = "MONKEY_GATEWAY_TIMEOUT_SEGUNDOS";

        public const string KAFKA_BOOTSTRAP_SERVERS = "KAFKA_BOOTSTRAP_SERVERS";
        public const string KAFKA_CONSUMER_GROUP_ID = "KAFKA_CONSUMER_GROUP_ID";
    }
}
